/* Bilingual copy. Loaded first. These classic scripts share one page scope, in this order. */
const T={
 doc_title:['North Oil Company for Kids','شركة نفط الشمال للأطفال'],
 brand:['North Oil Company','شركة نفط الشمال'],
  langBtn:['عربي','English'],
  snd_off:['Turn sound off','إيقاف الصوت'], snd_on:['Turn sound on','تشغيل الصوت'],
  back:['Back','رجوع'], next:['Next','التالي'], fs:['Full screen','ملء الشاشة'], slide:['Slide {n}','الشريحة {n}'],
  resetBtn:['Start over from the beginning','لنبدأ من جديد'],
 m_sky:['Sky','السماء'], m_sea:['Sea','البحر'], m_rock:['Rock','الصخور'], m_oil:['Oil','النفط'],
 s1_h:['Let’s explore the sea with North Oil Company!','هيا نستكشف البحر مع شركة نفط الشمال!'],
 s1_p:['Hi! I’m <b>Qatra</b>, a little drop of oil. Come with me on an adventure deep under the sea!','مرحبًا! أنا <b>قطرة</b>، قطرة نفط صغيرة. تعالوا معي في مغامرة إلى أعماق البحر!'],
 s1_btn:['Start the adventure','لنبدأ المغامرة'],
 s2_h:['Who is North Oil Company?','من هي شركة نفط الشمال؟'],
 s2_p:['A Qatari company that has been bringing oil up from under the sea since 2017.','شركة قطرية تستخرج النفط من تحت البحر منذ عام 2017.'],
  s2_p2:['It has two partners. Imagine a cake cut into 10 pieces:','ولها شريكان. تخيّلوا كعكة مقسّمة إلى 10 قطع:'],
 s2_qe:['<b>QatarEnergy</b> has 7 pieces (70%)','<b>قطر للطاقة</b> لها 7 قطع (70%)'],
 s2_te:['<b>TotalEnergies</b> has 3 pieces (30%)','<b>توتال إنرجيز</b> لها 3 قطع (30%)'],
 s2_cake:['A cake with 7 red pieces and 3 yellow pieces','كعكة فيها 7 قطع حمراء و3 قطع صفراء'],
 s3_h:['Where is the oil?','أين يوجد النفط؟'],
  s3_p:['In the <b>Al-Shaheen field</b>, out in the sea about 80 km north of Ras Laffan.','في <b>حقل الشاهين</b>، في عرض البحر، على بُعد نحو 80 كم شمال رأس لفان.'],
 s3_p2:['It’s Qatar’s biggest oil field in the sea, and one of the biggest sea oil fields in the world!','إنه أكبر حقل نفط بحري في قطر، ومن أكبر حقول النفط البحرية في العالم!'],
 s3_img:['Map of Qatar showing the Al-Shaheen field in the sea, north of Ras Laffan','خريطة قطر تُظهر حقل الشاهين في البحر شمال رأس لفان'],
 map_qatar:['Qatar','قطر'], map_doha:['Doha','الدوحة'], map_rl:['Ras Laffan','رأس لفان'], map_sh:['Al-Shaheen','الشاهين'], map_km:['≈ 80 km','≈ 80 كم'],
 s4_h:['How do workers get there?','كيف يصل العاملون إلى هناك؟'],
  s4_p:['They fly by helicopter 🚁 and land right on top of the platform!','يطيرون بالمروحية 🚁 وتهبط بهم فوق المنصة مباشرة!'],
  s4_p2:['They stay for weeks at a time. The platform has bedrooms, a kitchen and even a gym!','ويعيشون هناك لأسابيع، ففي المنصة غرف نوم ومطبخ وحتى صالة رياضية!'],
 s4_jobs:['Jobs at sea','وظائف في البحر'],
 j1:['<b>Engineer</b> fixes big machines','<b>المهندس</b> يُصلح الآلات الكبيرة'],
  j2:['<b>Geologist</b> reads the rocks','<b>الجيولوجي</b> يدرس الصخور'],
 j3:['<b>Safety officer</b> keeps everyone safe','<b>مسؤول السلامة</b> يحافظ على سلامة الجميع'],
 j4:['<b>Chef</b> cooks for the crew','<b>الطاهي</b> يطبخ للفريق'],
 j5:['<b>Medic</b> helps anyone who feels sick','<b>المسعف</b> يعتني بمن يشعر بالتعب'],
  j6:['<b>Pilot</b> flies the helicopter','<b>الطيار</b> يقود المروحية'],
 s5_h:['Safety first! Let’s get Qatra ready','السلامة أولاً! لنجهّز قطرة'],
  s5_p:['Tap each item to put it on:','اضغطوا على كل قطعة حتى نلبسها لقطرة:'],
 s5_img:['Qatra the oil drop wearing safety gear','قطرة ترتدي معدات السلامة'],
  g_hat:['Hard hat','خوذة'], g_glasses:['Safety glasses','نظارة واقية'], g_ears:['Ear protection','واقي الأذن'], g_vest:['Safety vest','سترة السلامة'], g_gloves:['Gloves','قفازات'], g_boots:['Safety boots','حذاء السلامة'],
  tapHere:['Tap here!','اضغط هنا!'],
 g_count:['{n} of 6','{n} من 6'],
 g_done:['All set! Qatra is ready to go offshore ✅','رائع! قطرة جاهزة للذهاب إلى المنصة ✅'],
  s5_stop:['✋ <b>Everyone</b> can say “STOP” if something looks unsafe, even the newest worker!','✋ يمكن <b>لأي شخص</b> أن يقول «توقف» إذا رأى شيئًا غير آمن، حتى الموظف الجديد!'],
  dg_h:['Let’s drill together!','لنحفر معًا!'],
  dg_world:['Offshore platform, a drill going down through the sea, the seabed and the rock layers into an oil and gas reservoir.','منصة بحرية، ومثقاب ينزل عبر البحر وقاع البحر وطبقات الصخور إلى خزان النفط والغاز.'],
  dg_s0:['DRILL','احفر'], dg_s1:['FIND','اكتشف'], dg_s2:['LIFT','ارفع'], dg_s3:['COLLECT','اجمع'], dg_s4:['REFINERY','المصفاة'],
  dg_pull:['PULL TO DRILL','اسحبوا للحفر'], dg_pull2:['PULL TO LIFT','اسحبوا للرفع'],
  dg_p_tap_n:['Tap 3 sea animals to start drilling ({n}/3)','اضغطوا على 3 كائنات بحرية لبدء الحفر ({n}/3)'],
  dg_p_drilling:['Drilling deeper…','نحفر أعمق…'],
  dg_p_found:['We found oil and gas!','وجدنا النفط والغاز!'],
  dg_p_rising:['The oil is rising!','النفط يتصاعد!'],
  dg_p_collect:['Filling the storage tanks…','نملأ خزانات التخزين…'],
  dg_p_load:['Loading the tanker…','نحمّل الناقلة…'],
  dg_p_fill:['Oil is flowing to the tanker…','النفط يتدفق إلى الناقلة…'],
  dg_sail:['SET SAIL','لنُبحر'],
  dg_p_sail:['Sailing to the refinery…','نبحر إلى المصفاة…'],
  dg_p_done:['You did it!','أحسنتم!'],
  dg_b_found:['WE FOUND OIL & GAS!','وجدنا النفط والغاز!'],
  dg_b_found_cta:['BRING IT UP','لنرفعه'],
  dg_b_ready:['Ready to travel!','جاهزون للإبحار!'],
  dg_b_done:['🎉 You did it!','🎉 أحسنتم!'],
  dg_again:['PLAY AGAIN','العبوا من جديد'],
  dg_depth:['DEPTH','العمق'], dg_rising:['OIL RISING','صعود النفط'], dg_loading:['LOADING','التحميل'],
  dg_m:['m','م'],
  dg_lbl_ref:['REFINERY','المصفاة'],
  dg_lbl_sea:['SEA','البحر'], dg_lbl_seabed:['SEABED','قاع البحر'], dg_lbl_rock:['ROCK','الصخور'],
  dg_lbl_gas:['GAS','الغاز'], dg_lbl_oil:['OIL','النفط'],
  dg_slider:['Drill and lift joystick','عصا الحفر والرفع'],
  /* Al-Shaheen sea life — species documented in and around the field (tap one to learn its name) */
  dl_whaleshark:['Whale shark','القرش الحوت'],
  dl_whaleshark_f:['Gathers here to eat plankton.','يتجمع هنا ليتغذى على العوالق.'],
  dl_dolphin:['Spinner dolphin','الدولفين الدوار'],
  dl_dolphin_f:['Spotted swimming in the field.','شوهد يسبح في الحقل.'],
  dl_turtle:['Sea turtle','سلحفاة البحر'],
  dl_turtle_f:['Visits the field; holds its breath long.','يزور الحقل ويَكتم أنفاسه طويلًا.'],
  dl_hammerhead:['Hammerhead shark','قرش المطرقة'],
  dl_hammerhead_f:['A key shark and ray area.','منطقة مهمة للقروش وأسماك الراي.'],
  dl_ray:['Ray','سمكة الراي'],
  dl_ray_f:['Glides over the seabed like a carpet.','ينزلق فوق القاع كسجادة.'],
  dl_seasnake:['Sea snake','ثعبان البحر'],
  dl_seasnake_f:['Lives in Qatar’s offshore waters.','يعيش في مياه قطر.'],
  dl_hamour:['Hamour (grouper)','الهامور'],
  dl_hamour_f:['Platforms work like artificial reefs.','المنصات تعمل كشعاب اصطناعية.'],
  dl_butterfly:['Butterflyfish','سمكة الفراشة'],
  dl_butterfly_f:['Swims around the platform legs.','يسبح حول أرجل المنصة.'],
  dl_angelfish:['Arabian angelfish','السمكة الملائكية العربية'],
  dl_angelfish_f:['A colourful Gulf fish.','سمكة خليجية ملونة.'],
  dl_seabream:['Two-bar seabream','أسماك الشعري'],
  dl_seabream_f:['Swims in schools near platforms.','يسبح في أسراب قرب المنصات.'],
  dl_oyster:['Pearl oyster','محارة اللؤلؤ'],
  dl_oyster_f:['Grows on platform legs; Qatar pearls!','ينمو على أرجل المنصة؛ لؤلؤ قطر!'],
  dl_sponge:['Sponge','الإسفنج'],
  dl_sponge_f:['Pumps water to feed.','يضخ الماء ليتغذى.'],
  dl_brittlestar:['Brittle star','نجم البحر الهش'],
  dl_brittlestar_f:['Wriggles over the seabed.','يزحف على قاع البحر.'],
  dl_coral:['Coral','المرجان'],
  dl_coral_f:['Looks like a plant but is an animal!','يشبه النبات لكنه حيوان!'],
  dl_plankton:['Phytoplankton','العوالق النباتية'],
  dl_plankton_f:['Microscopic food for fish and whale sharks.','غذاء مجهري للأسماك والقرش الحوت.'],
  dl_algae:['Marine algae','الطحالب البحرية'],
  dl_algae_f:['Grows on the platform legs; makes oxygen.','ينمو على أرجل المنصة وينتج الأكسجين.'],
  s6_h:['Giant tables in the sea','طاولات عملاقة في البحر'],
  s6_p:['Al-Shaheen has <b>33 platforms</b>. They stand on long steel legs, like giant tables!','في حقل الشاهين، <b>33 منصة</b> تقف على أرجل فولاذية طويلة، مثل طاولات عملاقة!'],
  s6_p2:['The sea there is about <b>60 m</b> deep. That’s as tall as a 20-floor building!','عمق البحر هناك نحو <b>60 مترًا</b>، أي بارتفاع مبنى من 20 طابقًا!'],
  s6_p3:['More than <b>300 wells</b> help bring the oil up.','وأكثر من <b>300 بئر</b> تساعد على استخراج النفط.'],
  s6_tag:['60 m ≈ 20 floors','60 م ≈ 20 طابقًا'],
  s7_h:['How was oil made?','كيف يتكوّن النفط؟'],
  s7_1:['Millions of years ago, tiny sea plants and creatures lived in the water.','قبل ملايين السنين، عاشت نباتات وكائنات بحرية صغيرة جدًا في الماء.'],
  s7_2:['When they died, they sank to the bottom and got buried under mud and sand.','وعندما ماتت، غاصت إلى القاع ودُفنت تحت الطين والرمل.'],
  s7_3:['Heat and heavy rocks squeezed them for millions of years, and they slowly turned into oil!','ثم ضغطتها الصخور الثقيلة، وسخّنتها حرارة الأرض لملايين السنين، فتحولت ببطء إلى نفط!'],
  s7_sponge:['🧽 Oil hides in tiny holes inside the rock, like water in a sponge!','🧽 يختبئ النفط في ثقوب صغيرة جدًا داخل الصخور، مثل الماء في الإسفنجة!'],
 s8_h:['Wells that bend like a straw!','آبار تنحني مثل المصّاصة!'],
  s8_p:['The oil layer here is thin, sometimes only about 6 m thick. So engineers drill down, then turn sideways to follow it, like a bendy straw 🥤','طبقة النفط هنا رقيقة، وأحيانًا لا يزيد سمكها على 6 أمتار. لذلك يحفر المهندسون إلى الأسفل، ثم ينعطفون جانبياً ليتبعوا طبقة النفط، مثل المصّاصة 🥤'],
 s8_btn:['Drill again','لنحفر مرة أخرى'],
 s8_found:['Oil found! 🎉','وجدنا النفط! 🎉'],
  s8_rec:['🏆 <b>World record in 2008:</b> a well here was 12.3 km long. That’s about 40 Aspire Towers lying in a row! It took only 36 days to drill.','🏆 <b>رقم قياسي عالمي عام 2008:</b> حُفرت هنا بئر بطول 12.3 كم، أي ما يعادل نحو 40 برجًا بارتفاع برج أسباير (الشعلة) إذا مُدّت في صف واحد! واستغرق حفرها 36 يومًا فقط.'],
 d_sea:['Sea','البحر'], d_rock:['Rock','الصخور'], d_oil:['Oil layer','طبقة النفط'],
 s9_h:['How much oil?','كم كمية النفط؟'],
 s9_about:['About','حوالي'],
 s9_unit:['barrels of oil every day','برميل من النفط كل يوم'],
  s9_p:['That could fill about <b>19 Olympic swimming pools</b>, every single day!','وهذا يكفي لملء نحو <b>19 مسبحًا أولمبيًا</b> كل يوم!'],
  s9_p2:['That’s almost half of all Qatar’s oil!','وهذا يعادل تقريبًا نصف نفط قطر كله!'],
 s9_p3:['🚢 Pipes carry the oil to giant storage ships. Then tankers take it all around the world.','🚢 تنقل الأنابيب النفط إلى سفن تخزين عملاقة، ثم تحمله الناقلات إلى أنحاء العالم.'],
 s10_h:['Oil is hiding in your things!','النفط مختبئ في أغراضكم!'],
 s10_p:['Tap each one to find out how:','اضغطوا على كل واحدة لتكتشفوا كيف:'],
 o1:['Crayons','أقلام التلوين'], o1r:['Wax made from oil','شمع مصنوع من النفط'],
 o2:['Game controllers','أذرع الألعاب'], o2r:['Plastic made from oil','بلاستيك من النفط'],
 o3:['Sneakers','الأحذية الرياضية'], o3r:['Rubbery soles','نعل مطاطي'],
 o4:['Toothbrush','فرشاة الأسنان'], o4r:['Nylon bristles','شعيرات من النايلون'],
 o5:['Sports shirts','الملابس الرياضية'], o5r:['Polyester fabric','قماش البوليستر'],
 o6:['Cars','السيارات'], o6r:['Petrol','البنزين'],
 o7:['Planes','الطائرات'], o7r:['Jet fuel','وقود الطائرات'],
 o8:['Roads','الطرق'], o8r:['Asphalt','الأسفلت'],
 qtag1:['🎁 Prize question 1 of 3','🎁 سؤال الجائزة 1 من 3'],
 qtag2:['🎁 Prize question 2 of 3','🎁 سؤال الجائزة 2 من 3'],
 qtag3:['🎁 Prize question 3 of 3','🎁 سؤال الجائزة 3 من 3'],
  qrule:['Closest answer wins a prize!','الإجابة الأقرب تفوز بالجائزة!'],
 hintBtn:['💡 Hint','💡 تلميح'], revealBtn:['👀 Reveal the answer','👀 اكشف الإجابة'], hideAns:['Hide the answer','أخفِ الإجابة'], reveal:['Reveal','اكشف'],
 p1_q:['What is H₂S?','ما هو H₂S؟'],
 p1_h:['Hint: it’s a gas that workers on the platform must watch out for. 👃','تلميح: إنه غاز يجب أن ينتبه له العاملون على المنصة. 👃'],
 p1_a:['Hydrogen sulfide (H₂S)','كبريتيد الهيدروجين (H₂S)'],
  p1_b:['A poisonous gas you can’t see, and it smells like <b>rotten eggs</b>. It can come up from deep underground with the oil and gas.','غاز سام لا نراه، ورائحته تشبه <b>رائحة البيض الفاسد</b>. وقد يخرج من أعماق الأرض مع النفط والغاز.'],
  p1_c:['🚨 Workers wear a <b>gas detector</b> that alarms if H₂S is near. When there’s a lot of it, your nose stops smelling it, so trust the detector, not your nose! If the alarm goes off, walk into the wind so the gas blows away from you, and go to the safe meeting point.','🚨 يحمل العاملون <b>جهاز كشف الغاز</b> الذي يُطلق إنذارًا إذا اقترب مستوى H₂S. وعندما يكون تركيز هذا الغاز مرتفعًا، قد يتوقف الأنف عن شمّه، لذلك نثق بالجهاز، لا بالأنف! وإذا انطلق الإنذار، نتحرك عكس اتجاه الريح حتى تحمل الريح الغاز بعيدًا عنا، ونتوجه إلى نقطة التجمّع الآمنة.'],
  p2_q:['How many litres of oil are in one barrel?','كم لترًا من النفط في البرميل الواحد؟'],
  p2_h:['Hint: it’s between 100 and 200. 🤔','تلميح: الرقم بين 100 و200. 🤔'],
  p2_a:['159 litres','159 لترًا'],
  p2_b:['That’s about enough to fill a bathtub! 🛁','هذا يكفي تقريبًا لملء حوض استحمام! 🛁'],
 p2_c:['Fun fact: oil isn’t really kept in barrels anymore. It travels in pipes and giant ships, but we still count it in barrels!','معلومة طريفة: لم يعد النفط يُحفظ في براميل، بل ينتقل في الأنابيب والسفن العملاقة، لكننا ما زلنا نعدّه بالبراميل!'],
  p3_q:['Where is the North Oil Tower located in Doha?','أين يقع برج نفط الشمال في الدوحة؟'],
  p3_h:['Hint: it’s a famous street along the Doha waterfront. 🛣️','تلميح: شارع شهير على واجهة الدوحة البحرية. 🛣️'],
  p3_a:['Corniche Street','شارع الكورنيش'],
  p3_b:['The North Oil Tower stands on the Doha Corniche, right by the sea — in the same city where our story starts!','يقع برج نفط الشمال على كورنيش الدوحة، قرب البحر مباشرة — في المدينة نفسها التي بدأت منها قصتنا!'],
  p3_c:['So the team on the platforms works far out at sea, while the company’s home is right here on the Corniche in Doha. 🏢🏙️','إذن يعمل الفريق على المنصات بعيدًا في البحر، بينما مقر الشركة هنا على كورنيش الدوحة. 🏢🏙️'],
 s12_h:['Great job, Offshore Heroes!','أحسنتم يا أبطال البحر!'],
 s12_p:['Today you learned how North Oil Company brings oil up from deep under the sea, safely!','تعلّمتم اليوم كيف تستخرج شركة نفط الشمال النفط من أعماق البحر بأمان!'],
  s12_p2:['Who wants to be an engineer one day? 🙋','من يريد أن يصبح مهندسًا يومًا ما؟ 🙋'],
  s12_btn:['Celebrate! 🎉','لنحتفل! 🎉'],
 /* Qatra narration — 3 short lines per slide, looped */
  say0:[['Hi! I’m Qatra.','A tiny drop of oil.','Let’s explore the sea!'],['مرحبًا! أنا قطرة.','قطرة نفط صغيرة.','هيا نستكشف البحر!']],
  say1:[['We’re a Qatari oil company.','QatarEnergy owns 7 slices.','TotalEnergies owns 3 slices.'],['نحن شركة نفط قطرية.','قطر للطاقة تملك 7 قطع.','وتوتال إنرجيز تملك 3 قطع.']],
  say2:[['My home is Al-Shaheen.','It’s 80 km north of Ras Laffan.','One of the biggest sea fields!'],['بيتي في حقل الشاهين.','على بعد 80 كم شمال رأس لفان.','من أكبر الحقول البحرية!']],
  say3:[['Workers come by helicopter.','They stay for weeks.','Engineers, chefs and pilots!'],['يصل العاملون بالمروحية.','ويبقون أسابيع.','مهندسون وطهاة وطيارون!']],
  say6:[['33 platforms in the sea.','Steel legs like giant tables.','The sea is 60 m deep!'],['33 منصة في البحر.','أرجل فولاذية كطاولات عملاقة.','عمق البحر 60 مترًا!']],
  say7:[['Made from tiny sea creatures.','Buried under mud and sand.','Heat and rocks made oil!'],['من كائنات بحرية صغيرة.','دُفنت تحت الطين والرمل.','الحرارة والصخور صنعت النفط!']],
  say8:[['The oil layer here is thin.','Wells bend like a straw.','One well was 12.3 km long!'],['طبقة النفط هنا رقيقة.','الآبار تنحني مثل المصّاصة.','بئر بطول 12.3 كم!']],
  say9:[['300,000 barrels every day.','That fills 19 big pools!','Half of all Qatar’s oil!'],['300 ألف برميل كل يوم.','تكفي لملء 19 مسبحًا!','نصف نفط قطر كله!']],
  say10:[['Oil hides in your crayons.','It’s in your shoes too.','Even your toothbrush!'],['النفط في أقلامك.','وفي حذائك أيضًا.','حتى فرشاة أسنانك!']],
  say11:[['Psst… a secret gas!','What do you think it is?','Hmm… guess its name!'],['بسّ… غاز سري!','ما رأيكم ما هو؟','همم… خمّنوا اسمه!']],
  say12:[['How many litres, hmm?','What do you think?','Guess a number!'],['كم لترًا يا تُرى؟','ما رأيكم؟','خمّنوا رقمًا!']],
  say13:[['Something huge sleeps below.','What could it be?','Hmm… guess, heroes!'],['شيء ضخم نائم بالأسفل.','ما يمكن أن يكون؟','همم… خمّنوا يا أبطال!']],
  say14:[['Great job, Heroes!','You explored the sea with me.','Who wants to be an engineer?'],['أحسنتم يا أبطال!','استكشفتم البحر معي.','من يريد أن يصبح مهندسًا؟']]
};
